AWS_COGNITO_USER_POOL_ID_DEV: ${env:AWS_COGNITO_USER_POOL_ID_DEV}
AWS_COGNITO_CLIENT_ID_DEV: ${env:AWS_COGNITO_CLIENT_ID_DEV}
AWS_DYNAMODB_TABLE_NAME_DEV: ${env:AWS_DYNAMODB_TABLE_NAME_DEV}
AWS_MY_REGION: ${env:AWS_MY_REGION}
CLOUDFRONT_URL: ${env:CLOUDFRONT_URL}
SENDER_EMAIL: ${env:SENDER_EMAIL}
