AWS_COGNITO_USER_POOL_ID: ${env:AWS_COGNITO_USER_POOL_ID}
AWS_COGNITO_CLIENT_ID: ${env:AWS_COGNITO_CLIENT_ID}
AWS_DYNAMODB_TABLE_NAME: ${env:AWS_DYNAMODB_TABLE_NAME}
AWS_MY_REGION: ${env:AWS_MY_REGION}
